import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainLayout } from "@/Components/Layout/MainLayout";
import { AuthContextProvider } from "@/contexts/authContext";
import { ProjectContextProvider } from "@/contexts/projectContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "3D Asset - Enlighten",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <ProjectContextProvider>
            <MainLayout>
              {children}
            </MainLayout>
          </ProjectContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
